apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-learn
  template:
    metadata:
      labels:
        app: docker-learn
    spec:
      containers:
        - name: docker-learn
          image: {{ .Values.deployment.image }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SERVER_PORT
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_URL
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PASSWORD