apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  POSTGRES_URL: {{ .Values.secret.db.url | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.global.postgresql.service.ports.postgresql | b64enc | quote }}
  POSTGRES_DB: {{ .Values.global.postgresql.auth.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.postgresqlPassword | b64enc | quote }}