apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: learn
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}