apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
data:
  SERVER_PORT: "{{ .Values.deployment.containerPort }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  POSTGRES_URL: {{ .Values.secret.db.url | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.global.postgresql.service.ports.postgresql | b64enc | quote }}
  POSTGRES_DB: {{ .Values.global.postgresql.auth.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.postgresPassword | b64enc | quote }}