server:
  port: ${DEMO_APP_SERVICE_PORT}
spring:
  application:
    name: docker-learn
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${DEMO_APP_POSTGRESQL_SERVICE_PORT}/postgres
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none