postgresql:
  enabled: true
  postgresqlDatabase: postgres
  postgresqlUsername: user
  postgresqlPassword: password
  service:
    port: "5432"

secret:
  db:
    url: task-postgresql

deployment:
  image: misha912/docker-learn:0.1.1
  containerPort: 8000

service:
  port: 9000
  type: NodePort

ingress:
  host: "arch.homework"
  path: "/otusapp/yakimenko($|/)(.*)"
  port: 9000
